use scott;
-- 11.⁠ ⁠WAQTD NUMBER OF EMPS AND TOTAL SALary needed to pay THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L'S IN THEIR NAMES
SELECT COUNT(*), SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%LL%';

-- 12.⁠ ⁠WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT deptno)
FROM EMP;

-- 13.⁠ ⁠WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'O' IN THEIR NAMES 
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%O%';
-- 14. WAQTD NUMBER OF EMPLOYEES HAVING ATLEAST 2 L'S IN THEIR NAMES
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%L%L%';

-- 15.⁠ ⁠WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30
SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = 30;

-- 16.⁠ ⁠WAQTD MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST 
SELECT MAX(SAL)
FROM EMP
WHERE JOB = 'ANALYST';
-- 17. WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT SAL)
FROM EMP;

-- 18.⁠ ⁠WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT JOB)
FROM EMP;

-- 19.⁠ ⁠WAQTD AVE SALARY GIVEN TO THE CLERK
SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'CLERK';

-- 20.⁠ ⁠WAQTD MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGER OR A CLERK
SELECT MIN(SAL)
FROM EMP
WHERE DEPTNO = 10 AND JOB IN ('MANAGER','CLERK');