use scott;
-- 1.⁠ ⁠WAQTD DEPTNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT
-- SELECT DEPTNO, COUNT(*) AS EMP_COUNT
-- FROM EMP
-- WHERE JOB = 'CLERK'
-- GROUP BY DEPTNO
-- HAVING COUNT(*)>1;    THIS IS WRONG ANSWER CORRECT ANSWER IS BELOW 

-- SELECT DEPTNO, COUNT(*) AS EMP_COUNT
-- FROM EMP
-- GROUP BY DEPTNO
-- HAVING SUM(CASE WHEN JOB = 'CLERK' THEN 1 ELSE 0 END) >= 2;


SELECT DEPTNO, COUNT(*) AS EMP_COUNT
FROM EMP
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE JOB = 'CLERK'
    GROUP BY DEPTNO
    HAVING COUNT(*) >= 2
)
GROUP BY DEPTNO;

--  2.⁠ ⁠WAQTD DEPTNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT
SELECT DEPTNO,SUM(SAL),count(*) as EMP_NO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 3;

--  3.⁠ ⁠WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEED 3800
SELECT JOB,COUNT(*)
FROM EMP
WHERE SAL > 1200
GROUP BY JOB
HAVING SUM(SAL) > 3800;

--  4.⁠ ⁠WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE DEPTNO IN (
    SELECT DEPTNO 
    FROM EMP 
    WHERE JOB = 'MANAGER'
    GROUP BY DEPTNO 
    HAVING COUNT(*) = 2
)
GROUP BY DEPTNO;
--  5.⁠ ⁠WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600.

SELECT JOB,MAX(SAL)
FROM EMP
GROUP BY JOB
HAVING MAX(SAL) > 2600; 

-- 6.⁠ ⁠WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(SAL) > 1;

-- 7.WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE
SELECT HIREDATE
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(HIREDATE) > 1;

--  8.⁠ ⁠WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THan 3000
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < 3000;

--  9.⁠ WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S'.
SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%'
GROUP BY DEPTNO
HAVING COUNT(*) > 2;

-- 10.⁠ ⁠WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000
SELECT JOB, MIN(SAL), MAX(SAL)
FROM EMP
GROUP BY JOB
HAVING MIN(SAL) > 1000 AND MAX(SAL) < 5000;