use scott;
-- 31.⁠ ⁠WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME
FROM EMP
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE ENAME = 'SCOTT') AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE dname = 'ACCOUNTING');

-- 32.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO');

-- 33.⁠ ⁠WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME, SAL
FROM EMP
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE ENAME = 'KING') AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING');

-- 34.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');

-- 35.⁠ ⁠WAQTD NAME, SAL, JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME,SAL,JOB,HIREDATE
FROM EMP
WHERE HIREDATE < ALL (SELECT HIREDATE FROM EMP WHERE ENAME = 'KING') AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'OPERATIONS');

-- 36.⁠ ⁠DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');

-- 37.⁠ ⁠WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT,
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%A%');

-- 38.⁠ ⁠WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800.
SELECT DNAME,LOC 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL = 800);

-- 39.⁠ ⁠WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);

-- 40.⁠ ⁠WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40.
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL AND DEPTNO = 40);

-- 51.⁠ ⁠WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME
FROM EMP
WHERE SAL > ALL ( SELECT SAL FROM EMP WHERE JOB = 'SALESMAN');

-- 52.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT *
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMP WHERE JOB = 'CLERK');

-- 53.⁠ ⁠WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY ARE EARNING LESS THAN ATLEST A MANAGER
SELECT ENAME, SAL 
FROM EMP
WHERE SAL < ANY (SELECT SAL FROM EMP WHERE JOB = 'MANAGER');

-- 54.⁠ ⁠WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMP WHERE JOB = 'MANAGER');

-- 55.⁠ ⁠WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB = 'MANAGER') AND SAL > ALL ( SELECT SAL FROM EMP WHERE JOB = 'CLERK');

-- 56.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND HIREDATE < ANY( SELECT HIREDATE FROM EMP WHERE JOB = 'SALESMAN');

-- 57.⁠ ⁠WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME IN ('ACCOUNTING','SALES'));

-- 58.⁠ ⁠WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN ('SMITH','KING', 'MILLER'));

-- 59.⁠ ⁠WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC IN ('NEW YORK','CHICAGO'));

-- 60.⁠ ⁠WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE ENPLOYEES OF DEPT 10
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE DEPTNO = 10);