use scott;
-- 1. WAQTO THE DNAME IN WHICH MAX EMPLOYEES ARE WORKING


-- SELECT DNAME
-- FROM DEPT
-- WHERE DEPTNO IN (SELECT DEPTNO
-- FROM EMP 
-- GROUP BY DEPTNO 
-- HAVING COUNT(*) IN (SELECT MAX(COUNT(*))
-- FROM EMP 
-- GROUP BY DEPTNO));

                 
SELECT DNAME
FROM dept
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    GROUP BY DEPTNO
    HAVING COUNT(*) IN (
        SELECT MAX(emp_count)
        FROM (
            SELECT COUNT(*) AS emp_count
            FROM EMP
            GROUP BY DEPTNO
        ) AS emp_counts
    )
);

-- 2. WAQTD THE NAMES OF THE EMPLOYEES EARNING MORE THAN MILLER OF ACCOUNTING DEPT
SElECT ENAME 
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'MILLER' AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'ACCOUNTING'));

-- 3.⁠ ⁠WAQTD 2ND MINIMUM SALARY
SELECT MIN(SAL)
FROM EMP
WHERE SAL > (SELECT MIN(SAL) FROM EMP );

-- 4.⁠ ⁠WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL)
FROM EMP 
WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL)
FROM EMP ))));

-- 5.⁠ ⁠WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMIUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL)
FROM EMP )));


-- 6.⁠ ⁠WAQTD EMPNO OF THE EMPLOYEE EARNING 2ND MAXIMUM SALARY
SELECT EMPNO
FROM EMP 
WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL)
FROM EMP ));


-- 7.⁠ ⁠WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL IN
(SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL)
FROM EMP )))));

-- 8.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd
SELECT *
FROM EMP
WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM EMP )); 

-- 9.⁠ ⁠WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT ENAME
FROM EMP
WHERE HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP WHERE HIREDATE < (SELECT MAX(HIREDATE) FROM EMP));

-- 10.⁠ ⁠WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE HIREDATE IN (SELECT MIN(HIREDATE) FROM EMP));

-- 11.⁠ ⁠WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUN SALARY
SELECT *
FROM EMP
WHERE SAL IN (SELECT MIN(SAL) FROM EMP WHERE SAL > 
				(SELECT MIN(SAL) FROM EMP WHERE SAL >
					(SELECT MIN(SAL) FROM EMP WHERE SAL >
						(SELECT MIN(SAL) FROM EMP WHERE SAL >
							(SELECT MIN(SAL) FROM EMP WHERE SAL >
								(SELECT MIN(SAL) FROM EMP WHERE SAL >
									(SELECT MIN(SAL) FROM EMP )))))));

-- 12.⁠ ⁠WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP )));



